export const LYDIA_LOAD_TRANSACTIONS = 'LYDIA_LOAD_TRANSACTIONS';
export const LYDIA_LOAD_USERS = 'LYDIA_LOAD_USERS';
export const LYDIA_LOADING_TRANSACTIONS_STATE = 'LYDIA_LOADING_TRANSACTIONS_STATE';
export const LYDIA_LOADING_USERS_STATE = 'LYDIA_LOADING_USERS_STATE';
